language: node_js

script:
  yarn format --validate && yarn test

before_deploy:
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  on:
    branch: master