language: elm
elm-test: 0.19.0-rev5

before_deploy:
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  on:
    branch: master