language: node_js
node_js:
  - lts/*

install:
  - yarn add --dev elm elm-test@0.19.0-beta8
cache:
  yarn: true
  directories:
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages

script:
  - yarn run elm-test

before_deploy:
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  on:
    branch: master